### ISSUE TITLE
lerna ERR! yarn run develop exited 1 in 'embed-examples' error Command failed with exit code 1.

### ISSUE THREAD

**Issue by ebasattend** [matterport/showcase-sdk-examples#68]
hi, I follow the instructions to run the examples but I get this error when I run any of the examples can anyone help me with this ? thanks.

lerna ERR! yarn run develop exited 1 in 'embed-examples'
error Command failed with exit code 1.

yarn run v1.22.19
$ lerna run develop --scope=embed-examples --stream
lerna notice cli v5.1.4
lerna notice filter including "embed-examples"
lerna info filter [ 'embed-examples' ]
lerna info Executing command in 1 package: "yarn run develop"
embed-examples: warning package.json: No license field
embed-examples: $ webpack-dev-server
embed-examples: i ｢wds｣: Project is running at http://localhost:8000/
embed-examples: i ｢wds｣: webpack output is served from /
embed-examples: i ｢wds｣: Content not from webpack is served from C:\Users\Arol\Desktop\showcase-sdk-examples-master\packages\embed-examples\dist
embed-examples: Error: error:0308010C:digital envelope routines::unsupported
embed-examples:     at new Hash (node:internal/crypto/hash:67:19)
embed-examples:     at Object.createHash (node:crypto:135:10)
embed-examples:     at module.exports (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\util\createHash.js:135:53)
embed-examples:     at NormalModule._initBuildHash (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:417:16)
embed-examples:     at handleParseError (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:471:10)
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:503:5
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:358:12
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
embed-examples: Error: error:0308010C:digital envelope routines::unsupported
embed-examples:     at new Hash (node:internal/crypto/hash:67:19)
embed-examples:     at Object.createHash (node:crypto:135:10)
embed-examples:     at module.exports (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\util\createHash.js:135:53)
embed-examples:     at NormalModule._initBuildHash (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:417:16)
embed-examples:     at handleParseError (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:471:10)
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:503:5
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:358:12
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
embed-examples: Error: error:0308010C:digital envelope routines::unsupported
embed-examples:     at new Hash (node:internal/crypto/hash:67:19)
embed-examples:     at Object.createHash (node:crypto:135:10)
embed-examples:     at module.exports (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\util\createHash.js:135:53)
embed-examples:     at NormalModule._initBuildHash (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:417:16)
embed-examples:     at handleParseError (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:471:10)
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:503:5
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:358:12
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
embed-examples: Error: error:0308010C:digital envelope routines::unsupported
embed-examples:     at new Hash (node:internal/crypto/hash:67:19)
embed-examples:     at Object.createHash (node:crypto:135:10)
embed-examples:     at module.exports (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\util\createHash.js:135:53)
embed-examples:     at NormalModule._initBuildHash (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:417:16)
embed-examples:     at handleParseError (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:471:10)
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:503:5
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:358:12
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
embed-examples: Error: error:0308010C:digital envelope routines::unsupported
embed-examples:     at new Hash (node:internal/crypto/hash:67:19)
embed-examples:     at Object.createHash (node:crypto:135:10)
embed-examples:     at module.exports (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\util\createHash.js:135:53)
embed-examples:     at NormalModule._initBuildHash (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:417:16)
embed-examples:     at handleParseError (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:471:10)
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:503:5
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:358:12
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
embed-examples: C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:133
embed-examples:                 if(isError) throw e;
embed-examples:                             ^
embed-examples: Error: error:0308010C:digital envelope routines::unsupported
embed-examples:     at new Hash (node:internal/crypto/hash:67:19)
embed-examples:     at Object.createHash (node:crypto:135:10)
embed-examples:     at module.exports (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\util\createHash.js:135:53)
embed-examples:     at NormalModule._initBuildHash (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:417:16)
embed-examples:     at handleParseError (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:471:10)
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:503:5
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\webpack\lib\NormalModule.js:358:12
embed-examples:     at C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:373:3
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
embed-examples:     at iterateNormalLoaders (C:\Users\Arol\Desktop\showcase-sdk-examples-master\node_modules\loader-runner\lib\LoaderRunner.js:221:10) {
embed-examples:   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
embed-examples:   library: 'digital envelope routines',
embed-examples:   reason: 'unsupported',
embed-examples:   code: 'ERR_OSSL_EVP_UNSUPPORTED'
embed-examples: }
embed-examples: Node.js v17.6.0
embed-examples: error Command failed with exit code 1.
embed-examples: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run develop exited 1 in 'embed-examples'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dmtaub** [comment]
It looks like it may be related to your node   version. The error is with
webpack libraries, not this sdk. What version of node are you using? Perhaps
try one of the solutions posted here:

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
